'use strict';
const D = window.GUIDE;
const $ = (s, root=document) => root.querySelector(s);
const $$ = (s, root=document) => [...root.querySelectorAll(s)];
const esc = v => String(v ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money = n => new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
const num = (n,d=2) => Number(n).toLocaleString('en-US',{maximumFractionDigits:d});
const qa = new URLSearchParams(location.search).get('qa')==='1';
const KEY = 'trc-rehearsal-build-guide-v1'+(qa?'-qa':'');
const defaults = () => ({schema:1,tasks:{},survey:{},prices:{},orders:{},surveyor:'',surveyDate:'',budget:{tax:0,shipping:0,contingency:15},waste:10});
let state=defaults(),storageOK=true;
try { const raw=localStorage.getItem(KEY); if(raw) state=normalize(JSON.parse(raw)); } catch { storageOK=false; }
function normalize(v){
  if(!v || v.schema!==1 || typeof v!=='object') throw Error('This file is not a build-guide progress backup.');
  const s=defaults();
  for(const phase of D.phases) for(const t of phase.tasks) s.tasks[t.id]=v.tasks?.[t.id]===true;
  for(const m of D.measurements){const x=v.survey?.[m.id];s.survey[m.id]={note:typeof x?.note==='string'?x.note.slice(0,10000):'',checked:x?.checked===true};}
  for(const p of D.items){const value=v.prices?.[p.id];if(value!=='' && value!=null && Number.isFinite(Number(value)) && Number(value)>=0 && Number(value)<1e8)s.prices[p.id]=Number(value);if(['Unpriced','Quoted','Ordered','Received','Installed','Retained'].includes(v.orders?.[p.id]))s.orders[p.id]=v.orders[p.id];}
  s.surveyor=typeof v.surveyor==='string'?v.surveyor.slice(0,200):'';s.surveyDate=/^\d{4}-\d{2}-\d{2}$/.test(v.surveyDate||'')?v.surveyDate:'';
  for(const k of ['tax','shipping','contingency']){const n=Number(v.budget?.[k]);if(Number.isFinite(n)&&n>=0&&n<=(k==='shipping'?1e7:100))s.budget[k]=n;}
  if(Number.isFinite(Number(v.waste))&&Number(v.waste)>=0&&Number(v.waste)<=50)s.waste=Number(v.waste);
  return s;
}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));storageOK=true;$('#save-state').textContent=qa?'QA copy · real progress untouched':'Saved in this browser';}catch{storageOK=false;$('#save-state').textContent='Storage unavailable · export a backup';toast('Browser storage is unavailable. Save a progress backup.');}}
let toastTimer;function toast(s){$('#toast').textContent=s;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),4200);}
function download(name,type,body){const url=URL.createObjectURL(new Blob([body],{type}));const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),2000);}
function backup(){download('rehearsal-room-progress-'+new Date().toISOString().slice(0,10)+'.json','application/json',JSON.stringify({...state,exportedAt:new Date().toISOString()},null,2));toast('Progress backup downloaded.');}
function csvCell(v){let s=String(v??'');if(/^[=+@\-]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';}
function exportCSV(){const head=['ID','Category','Item','Qty allowance','Unit','Trade','Specification','Release condition','Evidence','Recorded status','Line quote USD','Candidate links'];const rows=D.items.map(p=>[p.id,p.group,p.name,p.qty,p.unit,p.trade,p.spec,p.gate,p.source,state.orders[p.id]||'Unpriced',state.prices[p.id]??'',productsFor(p).map(x=>x.url).join(' | ')]);download(`rehearsal-room-shopping-v${D.version}.csv`,'text/csv;charset=utf-8','\ufeff'+[head,...rows].map(r=>r.map(csvCell).join(',')).join('\r\n'));toast('Shopping sheet downloaded with current quotes.');}
function productsFor(p){return D.products.filter(x=>(p.productCategories||[p.productCategory]).includes(x.category));}
function checkedTasks(){return Object.values(state.tasks).filter(Boolean).length;}
function taskCount(){return D.phases.reduce((n,p)=>n+p.tasks.length,0);}
function checkedSurvey(){return D.measurements.filter(m=>state.survey[m.id]?.checked).length;}
function list(a){return '<ul>'+a.map(t=>'<li>'+esc(t)+'</li>').join('')+'</ul>';}
function specList(s){return '<ul class="spec-bullets">'+s.split(/(?<=[.!?])\s+(?=[A-Z0-9])/).filter(Boolean).map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul>';}
function sourceLinks(){return D.sources.map(s=>`<div class="source-row"><a href="${esc(s.url)}" target="_blank" rel="noopener">${esc(s.title)} ↗</a><span>${esc(s.role)}</span></div>`).join('');}
function heading(k,title,sub){return `<div class="eyebrow">THE RECORDING CLUB / ${esc(k)}</div><h1>${title}</h1><div class="lede">${sub}</div>`;}
const installationItems = D.installation?.items || [];
const routeNames = {buy:'Buy + assemble',custom:'Custom fabrication',retain:'Retain + reinstall',service:'Survey / trade service'};
function installationCard(kit){
 const p=D.items.find(x=>x.id===kit.id);
 if(!p)return '';
 const materials=kit.materials.map(m=>`<li><div><strong>${esc(m.name)}</strong><span class="material-quantity">${esc(m.quantity)} ${esc(m.unit)}</span></div><span>${esc(m.spec)}</span><small>${esc(m.status)}${m.sourceUrl?` · <a href="${esc(m.sourceUrl)}" target="_blank" rel="noopener">Product / instructions ↗</a>`:''}</small></li>`).join('');
 return `<details class="install-card" id="install-${p.id}" data-install="${p.id}" data-route="${esc(kit.route)}"><summary><span class="install-id">${p.id}</span><span class="install-name">${esc(p.name)}<small>${esc(p.trade)} · ${kit.materials.length} material / service lines</small></span><span class="install-route">${esc(routeNames[kit.route]||kit.route)}</span></summary><div class="install-body"><div class="install-links"><a href="#drawings/${p.drawing}">${p.drawing} drawing →</a><a href="#buy" data-kit-buy="${p.id}">Quote this scope →</a></div><div class="install-columns"><section><h3>🧰 Gather the kit</h3><ul class="material-list">${materials}</ul><h3>Tools + access</h3>${list(kit.tools)}</section><section><h3>📋 Before starting</h3>${list(kit.before)}<h3>🛠 Install in this order</h3><ol class="install-steps">${kit.steps.map(step=>`<li>${esc(step)}</li>`).join('')}</ol><h3>✅ Accept the work when</h3>${list(kit.checks)}<div class="install-handoff"><h3>📐 Still required to release this work</h3>${list(kit.handoff)}</div></section></div><div class="install-sources"><h3>Manufacturer instructions + sources</h3>${kit.sources.length?kit.sources.map(s=>`<a href="${esc(s.url)}" target="_blank" rel="noopener">${esc(s.label)} ↗</a>`).join(''):'<span class="small">Custom or retained scope: collect the named shop drawings and actual equipment manuals before release.</span>'}</div></div></details>`;
}
function installationSection(){return `<section class="sheet" id="install">${heading('MATERIALS + INSTALLATION','Every element.<br>Its kit and its steps.',`${installationItems.length} scope cards: parts, tools, preparation, installation, acceptance and manufacturer sources.`)}<div class="actions"><a class="button primary" href="exports/material-kits-v${D.version}.csv" download>Download component list ↓</a><a class="button" href="exports/rehearsal-room-build-guide-v${D.version}.pdf" target="_blank">Full installation packet ↓</a><a class="button" href="#sequence">Work in build order →</a></div><div class="action-strip"><div><strong>📐 Field measurements release the custom work.</strong><span>These instructions cover the whole room. Quantities marked “field” and attachment, electrical and glazing details still need the named trade deliverables.</span></div><a class="button" href="#survey">Open the 16 field checks →</a></div><div class="facts"><div><strong>${installationItems.reduce((n,k)=>n+k.materials.length,0)}</strong><span>material + service lines</span></div><div><strong>${installationItems.reduce((n,k)=>n+k.steps.length,0)}</strong><span>ordered installation steps</span></div><div><strong>${installationItems.reduce((n,k)=>n+k.checks.length,0)}</strong><span>acceptance checks</span></div></div><div class="toolbar"><label>Find an element or material<input id="install-search" type="search" placeholder="Mirror adhesive, drivers, bar, platform…" autocomplete="off"></label><label>Work type<select id="install-route"><option value="">Every scope</option>${Object.entries(routeNames).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select></label><button data-action="expand-install">Expand shown cards</button><button data-action="collapse-install">Collapse all</button></div><div id="install-results" class="small" role="status"></div><div id="install-cards">${installationItems.map(installationCard).join('')}</div><div id="install-empty" class="empty" hidden>No matching kit. Clear the search or choose every scope.</div></section>`;}
const drawings=[
 {id:'A01',title:'Room + door plan',file:'room-plan.svg',summary:'Current furniture footprints at their issued poses; occupied fit still needs field proof.',facts:['North 146.25 in and west 259.5 in: printed facility dimensions; east-bay segments remain estimated.','D3 enters through the south wall at the west end, hinged west and swinging north.','Booth and vestibule follow the original 2024 plan; door offsets are traced, not field measured.','The plan uses the conservative 90.5 × 36 in Alpine envelope and two 24.75 × 29.5 in DYVLINGE chairs at their current rotations.'],gate:'Complete M-12 and M-16 together. Resolve the sofa 90 versus 90.5 in published-width discrepancy; tape actual furniture, occupied envelopes and both raised platforms.'},
 {id:'A02',title:'Mirror wall',file:'mirror-wall.svg',summary:'Five graduated arches match the current room proposal.',facts:['Five nominal 24 in-wide envelopes; heights 80 / 86 / 92 / 86 / 80 in.','Centers 13.5 / 43.3 / 73.14 / 103 / 132.8 in from the west corner.','Proposed span x=1.5–144.8 in; no cut sizes released.','Arch light length 76.37 ft net, excluding bottom edges.'],gate:'Glazier measures substrate, templates each arch, samples the finish and details support before fabrication.'},
 {id:'A03',title:'Bar + piano',file:'bar-piano.svg',summary:'The bar and piano match the displayed furniture arrangement.',facts:['Piano center 90 in south of the north wall; bar center 160 in.','Piano body 59⅛ in along the wall; bar length 48 in; proposed body gap 16.4375 in.','Bar depth 26 in; counter 42 in AFF; shelves at proposed 60/78 in AFF.','Three seats get 16 in of bar run per person; occupied fit is unresolved.'],gate:'Approve a full-size bar/stool/piano mockup and exact appliance cutout. Stone is templated after the base is installed.'},
 {id:'A04',title:'TV + instrument wall',file:'guitar-wall.svg',summary:'The TV belongs between the right-wall guitars and basses; actual bodies control the fit.',facts:['Bay face 102 in long; ceiling height 102 in is unverified.','Desk top 30 in; TV body and mount dimensions follow the selected model.','Template every physically present instrument body, headstock, yoke and removal arc.','Ten display positions are illustrated; verify the six inventoried instruments and the remaining display count on site.'],gate:'Complete M-13 with the selected TV and actual instruments. Greg approves the full-size elevation before backing heights, mount or hanger centers are fixed.'},
 {id:'E01',title:'Lighting + ceiling',file:'lighting-plan.svg',summary:'Keep light locations clear of the mirror inset.',facts:['Six proposed main-room downlights avoid the 96 × 96 in inset; two more serve the booth.','Track sits over the bay; separate booth light control.','192.13 ft net linear lighting across cove, graduated arches, inset and bar.','Run limits, accessible drivers and control protocol remain supplier design tasks.'],gate:'Electrician coordinates actual structure, ceiling/plenum, HVAC, existing safety devices and compatibility. Coordinates are planning points.'},
 {id:'A05',title:'Drum booth',file:'booth-plan.svg',summary:'Include the vestibule and both glass layers.',facts:['Current traced booth is behind a 29 in vestibule.','Approximate 10′3″ ×7′11″ body; curved/sloping wall reduces floor area.','Retain kit, desk, TV, mic boom and existing glass separation.','Doors and service access are field measurements.'],gate:'Survey the curve and slider assemblies. Confirm drum/desk access before absorber, cloud or floor orders.'},
 {id:'D01',title:'Build details',file:'assembly-details.svg',summary:'Use details to coordinate the trade handoffs.',facts:['Mirror light source is concealed and serviceable.','Wall fabric/core stays controlled until acoustic review.','Bar front vent and pull-out access remain open.','Ceiling mirror attachment is designed by the qualified support team.'],gate:'These are coordination sections. Manufacturer instructions and approved trade shop drawings control anchors, wiring, glass and substrate.'}
];
function render(){
 $('#content').innerHTML=`
 <section class="sheet" id="start">${heading(`BUILD GUIDE · v${D.version}`,'Build this room.<br>One step at a time.','A separate guide for the main room and drum booth, from the first measurement to the last sound check.')}
 <div class="actions"><a class="button primary" href="#install">Materials + installation →</a><a class="button" href="room-v${D.version}.html">Room image + furniture →</a><a class="button" href="layout.html">Move furniture →</a><a class="button" href="#survey">Open site checklist →</a><a class="button" href="exports/rehearsal-room-build-guide-v${D.version}.pdf" target="_blank">Open current build packet ↓</a><button data-action="print">Print current progress</button></div>
 <figure class="hero"><a href="assets/room-photo-v1.4.png" target="_blank"><img src="assets/room-photo-v1.4.png" width="1536" height="1024" alt="Approved rehearsal room concept with black gold mirror arches, compact bar, upright piano, charcoal lounge and guitar wall" fetchpriority="high"></a><figcaption><a href="assets/approved-concept.png" target="_blank">Original visual reference · September 13, 2026</a> · Current furniture + TV shown above. Exact dimensions come from the field record.</figcaption></figure>
 <div class="action-strip"><div><strong>⚠️ First visit: measure and tape the room.</strong><span>Custom orders stay held until the layout and supporting assemblies are approved.</span></div><a class="button" href="#survey">${D.measurements.length} field checks →</a></div>
 <div class="facts"><div><strong>${D.items.length}</strong><span>scoped purchase/quote lines</span></div><div><strong>${D.phases.length} phases</strong><span>from survey to handover</span></div><div><strong>${drawings.length} drawings</strong><span>plans, elevations and details</span></div><div><strong>${D.products.length} candidates</strong><span>manufacturer sources checked</span></div></div>
 <div class="split"><div class="panel"><h3>🎯 Start with these three actions</h3><ol class="scope-list"><li><b>01</b><span><a href="#survey">Book the survey</a> with the builder, electrician and AV lead; bring the actual instruments.</span></li><li><b>02</b><span><a href="#drawings">Tape the occupied layout</a>: bar, three stools, piano, lounge, desk, keys and door swings.</span></li><li><b>03</b><span><a href="#trades">Request scoped quotes</a>; sample lighting, mirrors, fabric and flooring before custom orders.</span></li></ol></div><div class="panel"><h3>🔍 Corrections already carried through</h3><ul class="scope-list"><li><b>✓</b><span>Latest local door/booth correction replaces the older three-door story.</span></li><li><b>✓</b><span>NU1X and Grandstage X use verified manufacturer envelopes.</span></li><li><b>✓</b><span>Fridge depth, guitar rows and ceiling support have explicit release checks.</span></li><li><b>✓</b><span>Each quote line connects to a drawing and trade scope.</span></li></ul></div></div>
 <div class="section-head"><h2>🔍 Keep the room you approved</h2></div><div class="split"><div class="panel">${list(['Five black/gold arched mirrors and a lit ceiling inset.','NU1X at the north end of the west wall, small bar to its south, and three stools.','Dark curved lounge seating, smoked-glass table and two swivels.','Fixed production desk with the TV between right-wall guitars and basses.','Warm 2700K lighting, charcoal finishes and black slats.','Separate drum booth and permanently connected seated-height Korg.'])}</div><div class="panel"><h3>Decisions needed at the mockup</h3>${list(['Furniture and occupied envelopes still need a full-size fit check.','The TV-and-instrument wall requires actual bodies and removal arcs.','Both raised storage-door platforms need the M-16 survey.','Dark-floor installation may require removing existing floating LVP.','Mirror support, exact wall finish and lighting control need coordinated trade details.'])}<a href="#drawings">See the holds on the drawings →</a></div></div>
 <div class="footnote">Quotation + coordination edition. Field sign-off and trade details release construction. Checkmarks record progress; they do not approve an order or certify the room.</div></section>

 <section class="sheet" id="drawings">${heading('ROOM + DRAWINGS','See where every part goes.','One coordinate frame, seven drawings, and the fit problems to resolve before fabrication.')}
 <div class="legend"><span><b>T</b> Typed tape dimension</span><span><b>P</b> Plan interpretation</span><span><b>D</b> Proposed design</span><span><b>V</b> Verified manufacturer size</span><span><b>F</b> Field check required</span></div>
 <div class="actions"><a class="button primary" href="layout.html">Arrange furniture on the interactive plan →</a><span class="small">Drag, rotate and save alternatives. Fixed drawing sheets stay separate.</span></div>
 <div class="tabbar" aria-label="Drawing sheets">${drawings.map(d=>`<a href="#drawings/${d.id}" data-drawing="${d.id}">${d.id} · ${d.title}</a>`).join('')}</div>
 <div class="drawing-stage"><figure class="drawing-canvas"><img id="drawing-image" src="assets/room-plan.svg" alt="Dimensioned rehearsal room coordination plan"></figure><aside class="drawing-detail" id="drawing-detail"></aside></div>
 <div class="legend"><span>All dimensions in inches unless marked.</span><span>Drawings are diagrams; do not scale from a printout.</span><span>AFF = above finished floor.</span></div>
 ${drawings.map(d=>`<figure class="print-only print-drawing"><h2>${d.id} · ${d.title}</h2><img src="assets/${d.file}" alt="${esc(d.title)}"><figcaption>${esc(d.gate)}</figcaption></figure>`).join('')}
 <div class="section-head"><h2>⚠️ Resolve the build conflicts here</h2></div>${D.conflicts.map(c=>`<article class="conflict"><h3>${esc(c.id)} · ${esc(c.title)}</h3><div><strong>Found:</strong> ${esc(c.evidence)}</div><div><strong>Next:</strong> ${esc(c.resolve)}</div><small>${esc(c.status)}</small></article>`).join('')}
 <div class="section-head"><h2>📊 Check the material allowances</h2></div><div class="panel calculator"><div><label>Floor waste allowance, percent <input type="number" min="0" max="50" step="1" id="waste" value="${state.waste}"></label><div class="footnote">Main room only for floor takeoff. Mirror/LED geometry is proposed. Booth and vestibule flooring require a separate measured takeoff.</div><a href="exports/quantity-calculations-v${D.version}.json" target="_blank">Open formulas and unrounded values ↗</a></div><div class="calc-results" id="calc-results"></div></div></section>

 <section class="sheet" id="sequence">${heading('BUILD SEQUENCE','Give every step a finish line.',`${D.phases.reduce((sum,phase)=>sum+phase.tasks.length,0)} checks in dependency order. Durations are planning allowances, not booking promises.`)}
 <div class="progress-line"><progress id="task-progress" max="${taskCount()}" value="${checkedTasks()}" aria-label="Build checklist progress"></progress><span id="task-count">${checkedTasks()} / ${taskCount()} checks recorded</span></div>
 <div class="warning">⚠️ Checking a task records your progress. Trade approvals and field-release conditions still apply.</div>
 ${D.phases.map((p,i)=>`<article class="phase"><div class="phase-num">${String(i+1).padStart(2,'0')}</div><div><div class="phase-title"><h2>${esc(p.title)}</h2><span class="count">${esc(p.id)}</span></div><div class="phase-meta"><span>${esc(p.owner)}</span><span>${esc(p.duration)}</span></div><details><summary>Ready to start when</summary>${list(p.ready_when)}</details>${p.tasks.map(t=>`<label class="checkline"><input type="checkbox" data-task="${t.id}" ${state.tasks[t.id]?'checked':''}><span><strong>${esc(t.text)}</strong><small>Pass: ${esc(t.check)}</small></span></label>`).join('')}<div class="phase-gate"><strong>Pause this phase if</strong>${p.stop_if.map(x=>esc(x)).join('<br>')}</div><div class="footnote">Depends on ${p.depends_on.length?p.depends_on.map(id=>esc(id)+' · '+esc(D.phases.find(x=>x.id===id)?.title||'')).join('; '):'site access and an agreed scope'}.</div></div></article>`).join('')}</section>

 <section class="sheet" id="buy">${heading('BUY + QUOTE','Order the right thing, once.','Start with samples and trade quotes. Custom dimensions remain held until their release checks pass.')}
 <div class="actions"><button class="primary" data-action="csv">Download shopping sheet ↓</button><a class="button" href="#trades">Open trade scopes →</a></div>
 <div class="buy-summary"><div><div class="note-label">Recorded line quotes</div><div class="big-number" id="quote-total">Unpriced</div><span class="small" id="quote-coverage"></span><span class="small" id="quote-adjusted"></span></div><div class="budget-inputs"><label>Tax allowance %<input data-budget="tax" type="number" min="0" max="100" step="0.1" value="${state.budget.tax}"></label><label>Freight allowance $<input data-budget="shipping" type="number" min="0" step="1" value="${state.budget.shipping}"></label><label>Contingency %<input data-budget="contingency" type="number" min="0" max="100" step="1" value="${state.budget.contingency}"></label></div></div>
 <div class="small">Enter a total line quote, including the full quantity. Blank means unpriced; zero means a confirmed zero-cost line. Tax is a planning allowance across entered lines. Resolve scope overlap before adding bids.</div>
 <div class="toolbar"><label>Find a part<input id="buy-search" type="search" placeholder="Try mirror, fridge, or BAR-01…" autocomplete="off"></label><label>Category<select id="buy-group"><option value="">All categories</option>${[...new Set(D.items.map(p=>p.group))].map(g=>`<option>${esc(g)}</option>`).join('')}</select></label><label>Show<select id="buy-show"><option value="all">All items</option><option value="unpriced">Unpriced lines</option><option value="hold">Held items</option><option value="candidate">Has product candidate</option></select></label></div>
 <div id="buy-results" class="small" role="status"></div><div id="items">${D.items.map(renderItem).join('')}</div><div id="buy-empty" class="empty" hidden>No matching parts. <button data-action="clear-filter">Clear filters</button></div>
 <div class="footnote">Manufacturer research checked September 28, 2026. Candidates are not approved orders; prices and lead times require quotes. Recorded statuses are local notes and do not place orders.</div></section>

 ${installationSection()}

 <section class="sheet" id="trades">${heading('TRADE SCOPES','Give each trade a complete brief.','Copy the scope into a quote request, attach the drawings, and collect a coordinated price. Nothing is sent automatically.')}
 ${D.trades.map(t=>`<article class="trade"><header><h2>🔍 ${esc(t.name)}</h2><button data-copy-trade="${t.id}">Copy quote brief</button></header><div class="trade-columns"><div><h3>Include in the price</h3>${list(t.scope)}<h3>Return with the quote</h3>${list(t.deliverables)}</div><div><h3>Accept the work when</h3>${list(t.acceptance)}<h3>Clarify exclusions</h3>${list(t.exclusions)}</div></div></article>`).join('')}
 <div class="section-head"><h2>✅ Keep and recommission existing gear</h2></div>${D.retained.map(r=>`<article class="conflict"><h3>${esc(r.name)}</h3><div><strong>Verify:</strong> ${esc(r.verify)}</div><div><strong>Action:</strong> ${esc(r.action)}</div></article>`).join('')}</section>

 <section class="sheet" id="survey">${heading('SITE MEASUREMENTS','Close the gaps in one visit.','Bring a laser, tape, level, low-tack tape, camera and the actual instruments. Record dimensions, photos and who checked them.')}
 <div class="actions"><a class="button primary" href="exports/site-survey-v${D.version}.pdf" target="_blank">Open blank survey PDF ↓</a><button data-action="backup">Save filled survey + progress ↓</button></div>
 <div class="survey-meta"><label>Measured by<input id="surveyor" name="surveyor" autocomplete="name" value="${esc(state.surveyor)}" placeholder="Name and trade…"></label><label>Visit date<input id="survey-date" name="survey-date" type="date" value="${esc(state.surveyDate)}"></label></div>
 <div class="progress-line"><progress id="survey-progress" max="${D.measurements.length}" value="${checkedSurvey()}" aria-label="Site checklist progress"></progress><span id="survey-count">${checkedSurvey()} / ${D.measurements.length} bundles recorded</span></div>
 <div class="warning">⚠️ Record to the trade's required precision. Any changed dimension updates the affected drawing; 2% is an escalation threshold, never a fabrication tolerance.</div>
 ${D.measurements.map(m=>`<article class="measurement"><header><h3>${esc(m.id)} · ${esc(m.title)}</h3><span class="status">Field record needed</span></header><div class="method">${esc(m.method)}</div><div class="record"><strong>Keep:</strong> ${esc(m.record)}</div><label class="field" for="note-${m.id}">Actual readings + photo references + any conflict</label><textarea id="note-${m.id}" data-measurement="${m.id}" placeholder="Dimensions in inches; photo IDs; measured by; exceptions…">${esc(state.survey[m.id]?.note||'')}</textarea><div class="measurement-footer"><label class="checkline"><input type="checkbox" data-survey-check="${m.id}" ${state.survey[m.id]?.checked?'checked':''}><span>Evidence recorded and checked</span></label><span>Unblocks: ${m.unlocks.map(esc).join(', ')}</span></div><div class="small">Source: ${esc(m.source_status)}</div></article>`).join('')}
 <div class="footnote">These fields save only in this browser and URL. Export a backup before changing device. A recorded measurement does not automatically change the drawings or release fabrication.</div></section>

 <section class="sheet" id="files">${heading('FILES + EVIDENCE','Take the whole guide with you.',`The printable packet and drawings are current v${D.version} exports. Save a progress backup to carry your notes between devices.`)}
 <div class="files-grid"><div class="file-card"><h3>📄 Complete build packet</h3><span class="small">Drawings, 37 material kits, installation steps, sequence, survey and trade handoffs.</span><a href="exports/rehearsal-room-build-guide-v${D.version}.pdf" target="_blank">Open v${D.version} PDF ↓</a></div><div class="file-card"><h3>📄 Blank site survey</h3><span class="small">${D.measurements.length} measurement bundles with space for readings and photo references.</span><a href="exports/site-survey-v${D.version}.pdf" target="_blank">Open survey PDF ↓</a></div><div class="file-card"><h3>📊 Shopping + quote sheet</h3><span class="small">All ${D.items.length} parts, quantities, source links and release conditions.</span><button data-action="csv">Download with current quotes ↓</button><br><a href="exports/shopping-list-v${D.version}.csv" download>Current v${D.version} CSV ↓</a></div><div class="file-card"><h3>💾 Your field notes + progress</h3><span class="small">Includes tasks, measurements, quotes and recorded order status.</span><button data-action="backup">Export backup ↓</button> <button data-action="import">Import backup…</button></div><div class="file-card"><h3>📐 Seven vector coordination drawings</h3><span class="small">Not to scale. Vector diagrams stay sharp at any zoom; written dimensions govern.</span>${drawings.map(d=>`<a href="assets/${d.file}" target="_blank">${d.id} · ${d.title} ↗</a><br>`).join('')}</div><div class="file-card"><h3>🔍 Calculations + source notes</h3><span class="small">Trace each quantity and see what changed from the source records.</span><a href="exports/quantity-calculations-v${D.version}.json" target="_blank">Quantity formulas ↗</a><br><a href="research/audit-findings.md" target="_blank">Source audit ↗</a><br><a href="research/procurement-notes.md" target="_blank">Manufacturer research ↗</a><br><a href="exports/rehearsal-room-sharing-kit-v1.6.2.zip" download>Complete offline room kit ↓</a></div></div>
 <div class="section-head"><h2>🔍 Know what each source proves</h2></div>${sourceLinks()}
 <div class="section-head"><h2>🔍 Manufacturer sources</h2></div>${D.products.map(p=>`<div class="source-row"><a href="${esc(p.url)}" target="_blank" rel="noopener">${esc(p.name)} ↗</a><span>Checked ${esc(p.verified_date)} · ${esc(p.status)}</span></div>`).join('')}
 <div class="comparison"><figure><a href="assets/current-room.jpeg" target="_blank"><img src="assets/current-room.jpeg" alt="Existing rehearsal room before the proposed rebuild" width="800" height="600" loading="lazy"></a><figcaption>Existing room reference; condition may have changed.</figcaption></figure><figure><a href="assets/booth-existing.jpg" target="_blank"><img src="assets/booth-existing.jpg" alt="Existing adjoining drum booth from walkthrough" width="800" height="600" loading="lazy"></a><figcaption>Existing booth, retained drum/vocal use.</figcaption></figure></div>
 <div class="footnote">Separate source repository and snapshot. Claude's project remains unchanged. Confidence: moderate for design intent; low for field dimensions, construction fit and budget until verified.</div></section>`;
 wire();updateBudget();updateQuantities();setRoute(false);filterItems(false);filterInstall();if(!storageOK)$('#save-state').textContent='Storage unavailable · export a backup';
}
function renderItem(p){const products=productsFor(p);return `<article class="item" data-item="${p.id}" data-group="${esc(p.group)}"><div class="item-head"><div class="item-title"><span class="id">${p.id} · ${esc(p.trade)}</span><h3>${esc(p.name)}</h3><span class="status ${/Hold/.test(p.status)?'':'blue'}">${/Hold/.test(p.status)?'! ':'↗ '}${esc(p.status)}</span></div><div class="qty"><strong>${num(p.qty)}</strong><small>${esc(p.unit)}</small></div><div class="price"><label for="price-${p.id}">Total line quote $</label><input id="price-${p.id}" data-price="${p.id}" type="number" min="0" step="1" inputmode="decimal" value="${state.prices[p.id]??''}" placeholder="Unpriced"></div><div class="order-state"><label for="order-${p.id}">Your record</label><select id="order-${p.id}" data-order="${p.id}">${['Unpriced','Quoted','Ordered','Received','Installed','Retained'].map(o=>`<option ${state.orders[p.id]===o?'selected':''}>${o}</option>`).join('')}</select></div></div><details><summary>Specification, release check${products.length?' + product source':''}</summary><div class="item-details"><div><h4>Specify this</h4>${specList(p.spec)}<div class="gate"><strong>Release only after:</strong> ${specList(p.gate)}</div><a href="#drawings/${p.drawing}">Open ${p.drawing} drawing →</a><br><a href="#install/${p.id}">Materials + installation steps →</a><div class="footnote">Basis: ${esc(p.source)}</div></div><div><h4>${products.length?'Manufacturer source + release gate':'Quote or confirm the actual item'}</h4>${products.length?products.map(x=>`<div class="product"><a href="${esc(x.url)}" target="_blank" rel="noopener">${esc(x.name)} ↗</a>${list(x.facts)}<div class="small">${esc(x.release_gate)}</div><details><summary>Manufacturer notes</summary><div class="small">${linkify(esc(x.notes))}</div></details></div>`).join(''):'<div class="subtle">Use this performance/finish specification in the trade quote. Ask for the exact manufacturer, size, lead time, exclusions and installation detail before approval.</div>'}</div></div></details></article>`;}
function linkify(s){return s.replace(/https:\/\/[^\s<>]+/g,x=>`<a href="${x}" target="_blank" rel="noopener">Source ↗</a>`);}
function setRoute(focus=true){let [tab,dr]=location.hash.slice(1).split('/');if(!['start','drawings','sequence','buy','install','trades','survey','files'].includes(tab))tab='start';$$('.sheet').forEach(e=>e.classList.toggle('active',e.id===tab));$$('#index-nav a').forEach(a=>a.setAttribute('aria-current',a.hash==='#'+tab?'page':'false'));$('.binder').classList.remove('menu-open');$('.menu-toggle').setAttribute('aria-expanded','false');const d=drawings.find(x=>x.id===dr)||drawings[0];$('#drawing-image').src='assets/'+d.file;$('#drawing-image').alt=d.title+' coordination drawing';$('#drawing-detail').innerHTML=`<h3>${esc(d.summary)}</h3><ul>${d.facts.map(x=>`<li>• ${esc(x)}</li>`).join('')}</ul><div class="warning">${esc(d.gate)}</div><a href="assets/${d.file}" target="_blank">Open large ${d.id} drawing ↗</a><a href="#buy">Find related parts →</a>`;$$('[data-drawing]').forEach(a=>a.setAttribute('aria-current',a.dataset.drawing===d.id?'true':'false'));document.title='Rehearsal Room 2 · '+({start:'Build guide',drawings:'Drawings',sequence:'Build sequence',buy:'Buy + quote',install:'Materials + installation',trades:'Trade scopes',survey:'Site survey',files:'Files + evidence'}[tab]);if(focus){window.scrollTo(0,0);$('#content').focus({preventScroll:true});}if(tab==='install'&&installationItems.some(k=>k.id===dr)){$('#install-search').value='';$('#install-route').value='';filterInstall();const card=$('#install-'+dr);card.open=true;requestAnimationFrame(()=>card.scrollIntoView({block:'start'}));}}
function updateBudget(){const entries=D.items.filter(p=>state.prices[p.id]!==undefined&&state.prices[p.id]!=='');const sum=entries.reduce((n,p)=>n+Number(state.prices[p.id]),0);$('#quote-total').textContent=entries.length?money(sum):'Unpriced';$('#quote-coverage').textContent=`${entries.length} of ${D.items.length} lines priced · ${D.items.length-entries.length} still unpriced`;const b=state.budget;const base=sum*(1+b.tax/100)+b.shipping;$('#quote-adjusted').textContent=entries.length?`${money(base*(1+b.contingency/100))} including entered allowances · partial total until every scope is priced`:'No project budget yet. Enter scoped quotes to build it.';}
function updateQuantities(){const q=window.BuildMath.takeoff(D.room.polygon,state.waste);$('#calc-results').innerHTML=`<div><strong>${num(q.area)} ft²</strong><small>Main-room net footprint</small></div><div><strong>${num(q.floorAllowance)} ft²</strong><small>Floor + ${state.waste}% waste</small></div><div><strong>${q.cartons} cartons</strong><small>At 23.64 ft²/carton</small></div><div><strong>${num(q.ledNet)} ft</strong><small>Linear lighting, net only</small></div><div class="calc-foot">Floor order area ${num(q.cartons*23.64)} ft². Lighting feeds, curved products and channel yields are specified separately. Allowances are not released orders.</div>`;}
function filterItems(writeURL=true){const q=$('#buy-search').value.trim().toLowerCase(),group=$('#buy-group').value,show=$('#buy-show').value;let n=0;for(const p of D.items){const yes=(!q||(p.id+' '+p.name+' '+p.spec+' '+p.trade).toLowerCase().includes(q))&&(!group||p.group===group)&&(show==='all'||show==='unpriced'&&state.prices[p.id]===undefined||show==='hold'&&/Hold/.test(p.status)||show==='candidate'&&productsFor(p).length>0);$(`[data-item="${p.id}"]`).hidden=!yes;if(yes)n++;}$('#buy-results').textContent=`${n} of ${D.items.length} items`;$('#buy-empty').hidden=n>0;if(writeURL){const u=new URL(location.href);for(const [k,v]of Object.entries({q,group,show:show==='all'?'':show})){if(v)u.searchParams.set(k,v);else u.searchParams.delete(k);}history.replaceState(null,'',u);}}
function filterInstall(){const q=$('#install-search').value.trim().toLowerCase(),route=$('#install-route').value;let n=0;for(const kit of installationItems){const p=D.items.find(x=>x.id===kit.id);const exact=installationItems.some(k=>k.id.toLowerCase()===q);const yes=(!q||(exact?kit.id.toLowerCase()===q:JSON.stringify([p?.name,p?.trade,kit]).toLowerCase().includes(q)))&&(!route||kit.route===route);const el=$(`[data-install="${kit.id}"]`);el.hidden=!yes;if(yes)n++;}$('#install-results').textContent=`${n} of ${installationItems.length} scope cards`;$('#install-empty').hidden=n>0;}
function wire(){
 $('#install-search').addEventListener('input',filterInstall);$('#install-route').addEventListener('change',filterInstall);
 $$('[data-kit-buy]').forEach(el=>el.addEventListener('click',()=>{$('#buy-search').value=el.dataset.kitBuy;$('#buy-group').value='';$('#buy-show').value='all';filterItems();}));
 $$('.checkline input[data-task]').forEach(el=>el.addEventListener('change',()=>{state.tasks[el.dataset.task]=el.checked;save();$('#task-progress').value=checkedTasks();$('#task-count').textContent=`${checkedTasks()} / ${taskCount()} checks recorded`;}));
 $$('[data-measurement]').forEach(el=>el.addEventListener('input',()=>{const id=el.dataset.measurement;state.survey[id]={...state.survey[id],note:el.value};save();}));
 $$('[data-survey-check]').forEach(el=>el.addEventListener('change',()=>{const id=el.dataset.surveyCheck;state.survey[id]={...state.survey[id],checked:el.checked};save();$('#survey-progress').value=checkedSurvey();$('#survey-count').textContent=`${checkedSurvey()} / ${D.measurements.length} bundles recorded`;}));
 $('#surveyor').addEventListener('input',e=>{state.surveyor=e.target.value;save();});$('#survey-date').addEventListener('change',e=>{state.surveyDate=e.target.value;save();});
 $$('[data-price]').forEach(el=>el.addEventListener('input',()=>{if(el.value===''){delete state.prices[el.dataset.price];}else{const n=Number(el.value);if(!Number.isFinite(n)||n<0||n>=1e8){el.setCustomValidity('Enter a nonnegative line quote below $100 million.');el.reportValidity();return;}el.setCustomValidity('');state.prices[el.dataset.price]=n;}save();updateBudget();filterItems(false);}));
 $$('[data-order]').forEach(el=>el.addEventListener('change',()=>{state.orders[el.dataset.order]=el.value;save();}));
 $$('[data-budget]').forEach(el=>el.addEventListener('input',()=>{const n=Number(el.value);if(!Number.isFinite(n)||n<0||n>(el.dataset.budget==='shipping'?1e7:100)){el.setCustomValidity('Enter a value in the allowed range.');el.reportValidity();return;}el.setCustomValidity('');state.budget[el.dataset.budget]=n;save();updateBudget();}));
 $('#waste').addEventListener('input',e=>{const n=Number(e.target.value);if(!Number.isFinite(n)||n<0||n>50){e.target.setCustomValidity('Use a waste allowance from 0% to 50%.');e.target.reportValidity();return;}e.target.setCustomValidity('');state.waste=n;save();updateQuantities();});
 const u=new URL(location.href);$('#buy-search').value=u.searchParams.get('q')||'';$('#buy-group').value=u.searchParams.get('group')||'';$('#buy-show').value=u.searchParams.get('show')||'all';if(!$('#buy-show').value)$('#buy-show').value='all';
 ['buy-search','buy-group','buy-show'].forEach(id=>$('#'+id).addEventListener(id==='buy-search'?'input':'change',()=>filterItems()));
 $$('[data-action]').forEach(el=>el.addEventListener('click',()=>{const a=el.dataset.action;if(a==='csv')exportCSV();if(a==='backup')backup();if(a==='print')window.print();if(a==='import')$('#import-file').click();if(a==='expand-install')$$('[data-install]').filter(x=>!x.hidden).forEach(x=>x.open=true);if(a==='collapse-install')$$('[data-install]').forEach(x=>x.open=false);if(a==='clear-filter'){$('#buy-search').value='';$('#buy-group').value='';$('#buy-show').value='all';filterItems();}}));
 $$('[data-copy-trade]').forEach(el=>el.addEventListener('click',async()=>{const t=D.trades.find(x=>x.id===el.dataset.copyTrade);const body=`TRC Rehearsal Room 2 / v${D.version} quote scope\n${t.name}\n\nInclude\n${t.scope.map(x=>'• '+x).join('\n')}\n\nReturn with the quote\n${t.deliverables.map(x=>'• '+x).join('\n')}\n\nAcceptance\n${t.acceptance.map(x=>'• '+x).join('\n')}\n\nClarify exclusions\n${t.exclusions.map(x=>'• '+x).join('\n')}\n\nQuote material, labor, freight, tax, lead time and exclusions separately. Confirm field measurements and submit shop drawings before custom orders. Attach the v${D.version} build packet. No construction release is implied.`;try{await navigator.clipboard.writeText(body);toast('Quote brief copied. Review and send it yourself.');}catch{download(`${t.id}-quote-brief-v${D.version}.txt`,'text/plain',body);toast('Clipboard unavailable. Quote brief downloaded.');}}));
}
window.BuildMath={takeoff(poly,waste=10){let twice=0,per=0;for(let i=0;i<poly.length;i++){const a=poly[i],b=poly[(i+1)%poly.length];twice+=a[0]*b[1]-b[0]*a[1];per+=Math.hypot(b[0]-a[0],b[1]-a[1]);}const area=Math.abs(twice)/288,perimeter=per/12,arches=[80,86,92,86,80].reduce((sum,h)=>sum+2*(h-12)+Math.PI*12,0)/12,ledNet=perimeter+arches+32+12;return {area,perimeter,arches,ledNet,floorAllowance:area*(1+waste/100),cartons:Math.ceil(area*(1+waste/100)/23.64),ledAllowance:ledNet*(1+waste/100)};},normalize};
window.addEventListener('hashchange',()=>setRoute());
window.addEventListener('popstate',()=>{const u=new URL(location.href);$('#buy-search').value=u.searchParams.get('q')||'';$('#buy-group').value=u.searchParams.get('group')||'';$('#buy-show').value=u.searchParams.get('show')||'all';filterItems(false);});
$('.menu-toggle').addEventListener('click',e=>{const on=!$('.binder').classList.contains('menu-open');$('.binder').classList.toggle('menu-open',on);e.currentTarget.setAttribute('aria-expanded',String(on));});
$('#backup-side').addEventListener('click',backup);
$('#import-file').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>2e6)throw Error('Backup is too large. Choose a build-guide JSON backup under 2 MB.');const incoming=normalize(JSON.parse(await file.text()));if(!confirm('Replace progress in this browser with this backup? Export your current backup first if you need to keep it.'))return;state=incoming;save();render();toast('Backup imported. Notes and progress restored.');}catch(err){toast(err.message||'This backup could not be read.');}finally{e.target.value='';}});
let printState=[];window.addEventListener('beforeprint',()=>{printState=$$('details').map(d=>[d,d.open]);$$('details').forEach(d=>d.open=true);$$('.print-record').forEach(e=>e.remove());$$('[data-measurement]').forEach(el=>{const note=document.createElement('div');note.className='print-only print-record';note.textContent=el.value||'No field note recorded.';el.after(note);});$$('[data-install]').forEach(el=>el.hidden=false);$$('[data-item]').forEach(el=>{el.hidden=false;const id=el.dataset.item,quote=document.createElement('div');quote.className='print-only print-record';quote.textContent=`Recorded status: ${state.orders[id]||'Unpriced'} · Line quote: ${state.prices[id]===undefined?'Unpriced':money(state.prices[id])}`;$('.item-head',el).append(quote);});});window.addEventListener('afterprint',()=>{printState.forEach(([d,on])=>d.open=on);$$('.print-record').forEach(e=>e.remove());filterItems(false);filterInstall();});
render();
