(function (root, factory) {
  const catalog = factory();
  if (typeof module === 'object' && module.exports) module.exports = catalog;
  if (root) root.FurnitureCatalog = catalog;
})(typeof globalThis !== 'undefined' ? globalThis : this, function () {
  'use strict';
  // W/D are the object's own axes. Its rotation places those axes in the room.
  // Published dimensions establish a product body, not ownership or installation clearance.
  const concept = 'assets/approved-concept.png';
  const audit = 'research/furniture-accuracy-v1.1.md';
  const records = {
    'SEAT-01': {name:'Craftmaster C9 · conversation sofa',profile:'curved-sofa',w:112,d:38,h:37,rotation:0,quality:'published',color:'#303035',source:'https://www.cmfurniture.com/design-options/c9/',sourceLabel:'Craftmaster C914256 · 2026 specifications',image:'assets/products/craftmaster-c9-conversation-sofa/official-room-scene.webp',note:'Craftmaster C914256: rounded panel arms, three loose boxed backs, three seat cushions, tapered Black legs. Published planning body 112 W × 38 D × 37 H in; arm 25 in, seat 20 in. Current manufacturer depth is 38 in; older dealer records differ. Proposed Robert Allen Revive Obsidian damask via the manufacturer’s COM program needs qualifying-dealer fabric approval, yardage and quote. Custom order, not stocked as shown. The 3D model reconstructs product photos; it is not manufacturer CAD.'},
    'SEAT-02A': {name:'HAY AAL 81 Soft · A',profile:'lounge-chair',w:30,d:28.75,h:32,rotation:215,quality:'published',color:'#34353b',source:'https://www.dwr.com/living-lounge-chairs/about-a-lounge-81-swivel-chair-low-back/100542267.html?lang=en_US',sourceLabel:'DWR · HAY AAL 81 Soft',image:'assets/products/hay-aal81-soft-obsidian-black/hero.jpg',note:'Selected purchasable chair: HAY AAL 81 Soft, Prone Obsidian leather, black four-star swivel base. Published outer body 30 W × 28¾ D × 32 H in; seat height 14¼ in. Two identical chairs. The rotated footprint follows the body; allow additional space for a person and a full swivel.'},
    'SEAT-02B': {name:'HAY AAL 81 Soft · B',profile:'lounge-chair',w:30,d:28.75,h:32,rotation:145,quality:'published',color:'#34353b',source:'https://www.dwr.com/living-lounge-chairs/about-a-lounge-81-swivel-chair-low-back/100542267.html?lang=en_US',sourceLabel:'DWR · HAY AAL 81 Soft',image:'assets/products/hay-aal81-soft-obsidian-black/hero.jpg',note:'Selected purchasable chair: HAY AAL 81 Soft, Prone Obsidian leather, black four-star swivel base. Published outer body 30 W × 28¾ D × 32 H in; seat height 14¼ in. Two identical chairs. The rotated footprint follows the body; allow additional space for a person and a full swivel.'},
    'SEAT-ALPINE': {name:'Jennifer Taylor Alpine · ebony black',profile:'alpine-sofa',w:90.5,d:36,h:27.5,rotation:0,quality:'published',color:'#202124',price:1252.99,source:'https://www.jennifertaylorhome.com/alpine-90-sherpa-sofa-ebony-black-boucle/',sourceLabel:'Jennifer Taylor Home · Alpine 64190-3-MBB',image:'assets/products/jennifer-taylor-alpine-ebony-black/official-three-quarter.jpg',note:'Affordable selected sofa: Jennifer Taylor Home Alpine 64190-3-MBB in ebony-black boucle, $1,252.99 sale price checked 2026-09-28. The official dimension graphic gives the conservative modeled envelope 90½ W × 36 D × 27½ H in, while the product text rounds width to 90 in. Seat 70½ W × 24 D × 17½ H in; arm 27½ in; natural-oak wedge feet 4 in high. Two removable seat cushions sit inside a continuous tight rounded back-and-arm frame. Confirm the half-inch width discrepancy before ordering; price and delivery availability must also be rechecked.'},
    'SEAT-DYVLINGE': {name:'IKEA DYVLINGE · Kelinge black',profile:'dyvlinge-chair',w:24.75,d:29.5,h:26.75,rotation:0,quality:'published',color:'#202125',price:199,source:'https://www.ikea.com/us/en/p/dyvlinge-swivel-chair-kelinge-black-80570831/',sourceLabel:'IKEA · DYVLINGE 805.708.31',image:'assets/products/ikea-dyvlinge-kelinge-black/official-front.jpg',note:'Affordable selected chair: IKEA DYVLINGE 805.708.31, Kelinge black textured polyester, $199 each checked 2026-09-28. Published outer body 24¾ W × 29½ D × 26¾ H in; seat 24¾ W × 18½ D × 16⅞ H in. Armless tufted seat/back on a chrome-plated five-star swivel base. Two layout instances share this catalog product. Delivery stock depends on ZIP and must be rechecked.'},
    'SEAT-03': {name:'Smoked-glass table',profile:'round-table',w:30,d:30,rotation:0,quality:'concept',color:'#5e626b',source:concept,sourceLabel:'Approved concept',note:'Proposed 30 in diameter. Round glass top and pedestal; actual product has not been selected.'},
    'BAR-01': {name:'Custom bar',profile:'bar',w:48,d:26,rotation:270,swapAxes:true,quality:'proposed',color:'#514039',source:audit,sourceLabel:'Custom millwork dimensions',note:'48 in long × 26 in deep proposed counter. Front faces east. South-end fridge bay is part of this assembly; final carcass and overhang need the millworker’s shop drawing.'},
    'BAR-06': {name:'Bar stool',profile:'stool',w:15,d:15,rotation:0,quality:'concept',color:'#504341',source:concept,sourceLabel:'Approved concept',note:'15 in diameter is the source seat allowance, not a verified stool product. Legs, foot ring and a seated person may need more space.'},
    'KEY-01': {name:'Yamaha NU1X',profile:'upright-piano',w:59.125,d:18.25,rotation:270,swapAxes:true,quality:'published',color:'#2c3138',source:'https://data.yamaha.com/files/download/other_assets/0/1103900/nu1x_en_om_a0.pdf',sourceLabel:'Yamaha NU1X manual · p44',note:'Published body: 59⅛ W × 18¼ D in. The keyboard faces east. Verify the instrument is an NU1X; older inventory calls it a Clavinova. Bench and playing clearance are separate.'},
    'BENCH-01': {name:'Piano bench',profile:'bench',w:30,d:14,rotation:270,swapAxes:true,quality:'unknown',color:'#48414a',source:audit,sourceLabel:'Bench measurement needed',note:'30 × 14 in is an unidentified bench allowance. Measure the actual seat and projecting legs; no manufacturer size is established.'},
    'DESK-01': {name:'Production desk',profile:'desk',w:72,d:32,rotation:90,swapAxes:true,quality:'proposed',color:'#404954',source:audit,sourceLabel:'Desk proposal + equipment',note:'72 × 32 in proposed desktop, facing west. Display, console, rack and two HS8 body diagrams travel with the desk. Exact desk model, supports and knee/service space remain unverified.'},
    'CHAIR-01': {name:'Engineer chair',profile:'office-chair',w:26,d:26,rotation:270,quality:'unknown',color:'#48515e',source:audit,sourceLabel:'Chair measurement needed',note:'26 × 26 in source allowance including five-star base. Exact chair, arms, caster reach and occupied clearance must be measured.'},
    'PMC-N': {name:'PMC north · model?',profile:'monitor',w:15.8,d:19.7,rotation:90,quality:'unknown',color:'#40464f',source:audit,sourceLabel:'Conflicting PMC dimensions',note:'15.8 × 19.7 in is the inherited inventory envelope, not a verified cabinet. IB1-family variants have different depths; the exact model and stand base must be identified. No new model substitution is implied.'},
    'PMC-S': {name:'PMC south · model?',profile:'monitor',w:15.8,d:19.7,rotation:90,quality:'unknown',color:'#40464f',source:audit,sourceLabel:'Conflicting PMC dimensions',note:'15.8 × 19.7 in is the inherited inventory envelope, not a verified cabinet. IB1-family variants have different depths; the exact model and stand base must be identified. No new model substitution is implied.'},
    'AV-PA': {name:'PA + tripod allowance',profile:'pa-stand',w:42,d:42,rotation:90,quality:'unknown',color:'#5b626b',source:audit,sourceLabel:'PA stand allowance',note:'The old 14 × 14 in box omitted the stand. This is a 42 in diameter tripod allowance from the inventory notes, not a field measurement. Cabinet identity, tripod leg reach and any wall-mount option need confirmation.'},
    'KORG-01': {name:'Korg Grandstage X',profile:'stage-piano',w:53.98,d:18.15,rotation:0,quality:'published',color:'#56544f',source:'https://www.korg.com/us/products/synthesizers/grandstage_x/specifications.php',sourceLabel:'Korg manufacturer specifications',note:'Published body: 53.98 W × 18.15 D in, excluding music stand. Keys face south. Stand feet, pedals, cables and the seated player need additional measured space.'},
    'BENCH-02': {name:'Keys bench',profile:'bench',w:24,d:12,rotation:0,quality:'unknown',color:'#49444c',source:audit,sourceLabel:'Bench measurement needed',note:'24 × 12 in is a source allowance for an unidentified bench. Verify seat and leg projection on site.'},
    'AMP-01': {name:'Fender Hot Rod Deluxe IV',profile:'amp',w:23.5,d:10.4375,rotation:180,quality:'published',color:'#55504b',source:'https://www.fender.com/products/hot-rod-deluxe-iv',sourceLabel:'Fender manufacturer specifications',note:'Published cabinet: 23½ W × 10⁷⁄₁₆ D in. Corrected the source’s rounded 10½ in depth. Confirm the owned unit is the IV; allow for rear connections.'},
    'AMP-02': {name:'Fender Rumble 500 V3',profile:'amp',w:19,d:14,rotation:180,quality:'published',color:'#55504b',source:'https://www.fender.com/products/rumble-500',sourceLabel:'Fender manufacturer specifications',note:'Published V3 cabinet: 19 W × 14 D in. The inherited 23.4 × 17.4 in inventory size was wrong for this model. Verify the generation on the actual unit; do not substitute a head or extension cabinet.'},
    'BOO-KIT': {name:'Drum kit + hardware',profile:'drum-kit',w:72,d:66,rotation:0,quality:'unknown',color:'#ddd6c9',source:audit,sourceLabel:'Booth photo + setup allowance',note:'72 × 66 in is the complete setup allowance. Drum/cymbal placement is a reference diagram, not measured hardware. Photos show Yamaha; inventory says Gretsch. Identify the retained kit and trace stands, throne and player space.'},
    'BOO-DESK': {name:'Booth desk',profile:'booth-desk',w:30,d:18,rotation:90,swapAxes:true,quality:'unknown',color:'#8a654d',source:audit,sourceLabel:'Existing booth desk · verify',note:'30 × 18 in is a photo-derived source allowance. Drawn as a wood top, four-leg desk and lower rack shelf. Measure the actual desk before relying on its fit.'}
  };
  return Object.freeze({version:2,records});
});
